BatuaShop2/Controllers/AuthorizationController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using BatuaShop2.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BatuaShop2.Controllers
{
    public class AuthorizationController : Controller
    {
        private readonly UserManager<Users> _userManager;
        private readonly SignInManager<Users> _signInManager;
        private AppDbContent _appDbContent;

        public AuthorizationController(UserManager<Users> userManager,
            SignInManager<Users> signInManager, AppDbContent appDbContent)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _appDbContent = appDbContent;
        }

        // GET
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult Secret()
        {
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> Login(string email, string password)
        {
            var user = await _userManager.FindByEmailAsync(email);
            if (user != null)
            {
                var result = await _signInManager.PasswordSignInAsync(user, password, false, false);
                if (result.Succeeded)
                {
                    var checkForManager = _appDbContent.UserRoles.FirstOrDefault(r => r.UserId.Equals(user.Id));
                    if (checkForManager != null)
                    {
                        return RedirectToAction("ManagerPage","UserPage"); 
                    }
                    return RedirectToAction("Page", "UserPage");
                }
            }

            return RedirectToAction("Login");
        }

        public IActionResult Login()
        {
            var u =  _userManager.GetUserAsync(User.Clone()).Result;
           
            if (u != null)
            {
                var checkForManager = _appDbContent.UserRoles.Where(r => r.UserId.Equals(u.Id)); if (checkForManager.Any())
                {
                    return RedirectToAction("ManagerPage","UserPage"); 
                }
                return RedirectToAction("Page", "UserPage");
            }
            return View();
        }

        [HttpPost]
        public async Task<RedirectToActionResult> Registration(string name, string password, string email, string secondName,
            string lastName)
        {
            var user = new Users()
            {
                UserName = email,
                Name = name,
                Email = email,
                SecondName = secondName,
                LastName = lastName
            };
            var result = await _userManager.CreateAsync(user, password);
            
            return RedirectToAction("Login");
        }

        public async Task<IActionResult> LogOut()
        {
            var signOut = _signInManager.SignOutAsync().IsCompleted;
            if (signOut)
                return RedirectToAction("Index", "Home");
            return RedirectToAction("Login");
        }

        public IActionResult Registration()
        {
            return View();
        }
    }
}

BatuaShop2/Views/Authorization/Index.cshtml
<h2>INDEX</h2>

BatuaShop2/Views/Authorization/Login.cshtml
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link href="~/css/Login.css" rel="stylesheet" media="screen">
    <title>Вход</title>
</head>
<body>
    <div class="jumbotron vertical-center">
        <div class="container">
            <div class="row-container">
                <div class="img-container">
                    <img src="~/img/LogInPage.jpg" class="img-form img-fluid" alt="">
                </div> 
                <div class="info-container">
                    <h1 class="shop-name">BookShop</h1>
                    <div id="login" class="user-info">
                        <div>
                            <form asp-action="Login" asp-controller="Authorization" method="post">
                                <input id="email" name="email" type="email" placeholder="Логин*" required/>
                                <input name="password" type="password" placeholder="Пароль*" class="" required/>
                                <button type="submit" class="btn1">Вход</button>
                            </form>
                        </div>
                        <div class="another-panel">
                            <a onclick="DisplayRegister()">Регистрация</a>
                        </div>
                    </div>
                    <div id="register" class="user-info">
                        <div>
                            <form asp-action="Registration" asp-controller="Authorization" method="post">
                                <div class="row">
                                    <div class="col-md-6">
                                        <input name="email" type="email" placeholder="Эл.почта*" class="form-control" required/>
                                    </div>
                                    <div class="col-md-6">
                                        <input name="password" type="password" placeholder="Пароль*" class="form-control" required/>
                                    </div>
                                </div>
                                <input name="secondName" type="text" placeholder="Фамилия*" class="form-control  my-2 p-2" required/>
                                <input name="name" type="text" placeholder="Имя*" class="form-control  my-2 p-2" required/>
                                <input name="lastName" type="text" placeholder="Отчество*" class="form-control my-2 p-2" required/>
                                <button type="submit" class="btn1">Регистрация</button>
                            </form>
                        </div>
                        <div class="another-panel">
                            <a style="text-decoration:none; color:inherit; cursor:pointer;" onclick="DisplayLogin()">Войти в аккаунт</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
            function DisplayRegister(){
                document.getElementById("login").style.display = "none";
                document.getElementById("register").style.display = "block";
            }
            function DisplayLogin(){
                document.getElementById("register").style.display = "none";
                document.getElementById("login").style.display = "block";
            }
    </script>
</body>

BatuaShop2/Views/Authorization/Registration.cshtml
<h2>Regisration Page</h2>

<form asp-action="Registration" asp-controller="Authorization" method="post">
    <input type="text" name="username" value=""/>
    <input type="text" name="password" value=""/>
    <button type="submit">
        Registration
    </button>
</form>

BatuaShop2/Views/Authorization/Secret.cshtml
<h2>SECRET</h2>