BatuaShop2/ViewModels/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BatuaShop2.Models;

namespace BatuaShop2.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Book> favBooks { get; set; }
    }
}

BatuaShop2/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BatuaShop2.Interfaces;
using BatuaShop2.Models;
using BatuaShop2.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BatuaShop2.Controllers
{
    public class BooksController : Controller
    {
        private readonly IAllBooks allBooks;
        private readonly IBookCategory allCategories;
        private readonly ShopCart _shopCart;
        private readonly UserManager<Users> _userManager;
        private readonly IFavourite _favourites;
        private int MaxBooksCount = 4;

        public BooksController(IAllBooks allBooks, IBookCategory bookCategory, ShopCart shopCart,
            UserManager<Users> userManager,
            IFavourite favourites)
        {
            this.allBooks = allBooks;
            this._favourites = favourites;
            this.allCategories = bookCategory;
            this._shopCart = shopCart;
            _userManager = userManager;
        }

        [Route("Books/List/")]
        [Route("Books/List/{category}")]
        [Route("Books/List/{category}/{page}")]
        public ViewResult List(string category = null, int page = 1)
        {
            List<Book> books = null;
            string bookCategory = "";
            var cat = allCategories.allCategories.FirstOrDefault(c => category != null && category.Equals(c.id.ToString()));
            if (cat != null)
            {
                books = allBooks.Books.Where(i => i.categoryId == cat.id || i.categoryName != null && i.categoryName.Equals(cat.categoryName))
                    .OrderBy(i => i.id).ToList();
                foreach (var book in books.ToList())
                {
                    book.categoryName = cat.categoryName;
                }
                bookCategory = category;
            }
            else
            {
                books = allBooks.Books.OrderBy(i => i.id).ToList();
            }

            List<int> pages = new List<int>();

            var bookCounter = (page - 1) * MaxBooksCount;
            
            if (page != 1)
                pages.Add(page-1);
            pages.Add(page);
            if (bookCounter + MaxBooksCount< books.Count())
                pages.Add(page + 1);

            var bookObject = new BooksListViewModel
            {
                allBooks = books.GetRange(bookCounter, Math.Min(MaxBooksCount, books.Count()-bookCounter)),
                currCategory = cat != null ? cat.id : 0,
                currCategoryName = cat != null ? cat.categoryName : "Все книги",
                pageNumbers = pages.ToArray(),
                selectedPage = page
            };

            ViewBag.Title = "Страница с книгами";
            return View(bookObject);
        }

        public ViewResult findBook(string searching)
        {
            IEnumerable<Book> books = null;
            searching.ToLower();
            books = allBooks.Books.Where(b => b.name.ToLower().StartsWith(searching));
            var bookObject = new BooksListViewModel
            {
                allBooks = books.ToList(),
                currCategory = 0
            };
            return View(bookObject);
        }

        [HttpPost]
        public bool AddToCart(int id)
        {
            var item = allBooks.Books.FirstOrDefault(i => i.id == id);
            if (item != null)
            {
                _shopCart.AddToCart(item);
                return true;
            }

            return false;
        }

        public async Task<bool> AddToFavourite(int bookId)
        {
            var u = _userManager.GetUserAsync(User.Clone()).Result;
            bool res = false;
            if (u != null)
            {
                res = await _favourites.addFavourite(u.Id, bookId);
            }
            return res;
        }
    }
}

BatuaShop2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using BatuaShop2.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BatuaShop2.Models;
using BatuaShop2.ViewModels;

namespace BatuaShop2.Controllers
{
    public class HomeController : Controller
    {
        private IAllBooks bookRep;

        public HomeController(IAllBooks newBookRep)
        {
            bookRep = newBookRep;
        }

        public ViewResult Index()
        {
            return View();
        }

        public RedirectToActionResult RemoveFromFav(int id)
        {
            bookRep.RemoveFromFavourite(id);
            return RedirectToAction("Index");
        }
    }
}

BatuaShop2/Controllers/OneBookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BatuaShop2.Interfaces;
using BatuaShop2.Models;
using BatuaShop2.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BatuaShop2.Controllers
{
    public class OneBookController : Controller
    {
        private readonly IAllBooks allBooks;
        private readonly ShopCart _shopCart;
        private readonly IFavourite _favourite;
        private readonly UserManager<Users> _userManager;

        public OneBookController(IAllBooks allBooks, ShopCart shopCart, IFavourite favourite, UserManager<Users> userManager)
        {
            this.allBooks = allBooks;
            this._shopCart = shopCart;
            this._favourite = favourite;
            _userManager = userManager;
        }

        public async Task<ViewResult> GetOneBook(int id)
        {
            var selectedBook = allBooks.getObjectBook(id);

            List<Book> sameBooks = allBooks.Books.Where(b =>
                (b?.categoryId == selectedBook.categoryId || b.categoryName != null && b.categoryName.Equals(selectedBook.categoryName))
                && b.id != selectedBook.id).ToList();

            var u = await _userManager.GetUserAsync(User.Clone());
            bool isFavourite = false;

            if (u != null)
            {
                var favs = await _favourite.getFavourites(u.Id);
                var thisBookIsFavourite = favs.Where(f => f.bookId == id);
                if (thisBookIsFavourite.Any())
                {
                    isFavourite = true;
                }
            }
            
            var oneBook = new OneBookViewModel
            {
                book = selectedBook,
                sameBooks = sameBooks.Count == 0 ? sameBooks : sameBooks.Take(Math.Min(sameBooks.Count, 3)).ToList(),
                isFavourite = isFavourite
            };


            return View(oneBook);
        }

        public RedirectToActionResult AddToCart(int id)
        {
            var item = allBooks.Books.FirstOrDefault(i => i.id == id);
            if (item != null)
            {
                _shopCart.AddToCart(item);
            }

            return RedirectToAction("GetOneBook", new {id = id});
        }
    }
}

BatuaShop2/Views/Home/Index.cshtml
@model BatuaShop2.ViewModels.HomeViewModel
<head>
    <link rel="stylesheet" href="~/css/TopStyle.css">
    <link rel="stylesheet" href="~/css/slider_style.css">
    <link rel="stylesheet" href="~/css/Genre.css">
    <link rel="stylesheet" href="~/css/Footer.css">
    <link rel="stylesheet" href="~/css/list_style.css" />
    <link type="text/css" rel="stylesheet" href="~/css/lightslider.css" />
</head>
<body style="margin:0;">
    <div id="Top" class="bg-img">
        <div id="Header">
            <div class="menu">
                <ul>
                    <li><a id="browse" onclick="showCategory()"><b class="browse">Категории</b></a></li>
                    <li style="float: right"><a href="../Authorization/Login"><img src="~/img/user.png" class="profile" alt="User"></a></li>
                    <li style="float: right"><a asp-controller="ShopCart" asp-action="Index"><img src="~/img/basket.png" class="profile" alt="Basket"></a></li>
                </ul>
            </div>
            @await Html.PartialAsync("ShowMenu")
        </div>
        <form >
            <div id="Search" class="mysearch-box">
                <label>
                    <input class="mysearch-txt" type="text" placeholder="Поиск книги" name="Searching">
                    <button class="search-btn" asp-controller="Books" asp-action="findBook" type="submit">
                        <img src="~/img/search.png" class="search" alt="Search">
                    </button>
                </label>
               
            </div>
        </form>
        
        <div id="Up_Logo">
            <img src="~/img/logo.svg" alt="logo_text">
        </div>
    </div>
    <div id="slideshow">
        <div id="myslider">
            <a asp-controller="OneBook" asp-action="GetOneBook" asp-route-id="16">
                <img src="~/img/SliderBook_1.png" alt="famous_book_1"></a>
            <a asp-controller="OneBook" asp-action="GetOneBook" asp-route-id="20">
                <img src="~/img/SliderBook_2.png" alt="famous_book_2"></a>
            <a asp-controller="OneBook" asp-action="GetOneBook" asp-route-id="15">
            <img src="~/img/SliederBook_3.png" alt="famous_book_3"></a>
        </div>
    </div>
    <!--1-->
<div id="slider_lists">
    <div class="list_margins">
        <ul>
            <div class="clearfix float-text">
                <div class="circle-img">
                    <img src="~/img/Ellipse_1.png">
                </div>
                <h1>Призеры премии 2020</h1>
                <button onclick="window.location.href='/Books/List'"> ВСЕ </button>
            </div>
            <ul class="cs-hidden">
                <li class="item-a"><a asp-controller="OneBook" asp-action="GetOneBook" asp-route-id="19"><img src="~/img/IT.jpg" class="box"></a></li>
                <li class="item-a"><a asp-controller="OneBook" asp-action="GetOneBook" asp-route-id="17"><img src="~/img/cover1__w220.jpg" class="box"></a></li>
                <li class="item-a"><a asp-controller="OneBook" asp-action="GetOneBook" asp-route-id="3"><img src="~/img/oryel.png" class="box"></a></li>
                <li class="item-a"><a asp-controller="OneBook" asp-action="GetOneBook" asp-route-id="11"><img src="~/img/teleport.png" class="box"></a></li>
                <li class="item-a"><a asp-controller="OneBook" asp-action="GetOneBook" asp-route-id="2"><img src="~/img/ego.png" class="box"></a></li>
            </ul>
        </ul>
    </div>
    <!--2-->
    <div class="list_margins">
        <ul>
            <div class="clearfix float-text">
                <div class="circle-img">
                    <img src="~/img/Ellipse_2.png">
                </div>
                <h1>Кулинария</h1>
                <button onclick="window.location.href='/Books/List'"> ВСЕ </button>
            </div>
            <ul class="cs-hidden">
                <li class="item-a"><a asp-controller="OneBook" asp-action="GetOneBook" asp-route-id="15"><img src="~/img/ramzi.jpg" class="box"></a></li>
                <li class="item-a"><a href="#"><img src="~/img/Book_2@2x.png" class="box"></a></li>
                <li class="item-a"><a href="#"><img src="~/img/Book_3@2x.png" class="box"></a></li>
                <li class="item-a"><a href="#"><img src="~/img/Book_4@2x.png" class="box"></a></li>
                <li class="item-a"><a href="#"><img src="~/img/Book_5@2x.png" class="box"></a></li>
            </ul>
        </ul>
    </div>
</div>
@await Html.PartialAsync("Footer")
</body>
<script>
    simpleslider.getSlider({
        container: document.getElementById('myslider'),
        prop: 'left',
        init: document.body.clientWidth,
        show: 0,
        end: -document.body.clientWidth,
        unit: 'px',
        delay: 6,
        duration: 2
    });

    let count = 0;
    function showCategory() {
        const category = document.getElementById("category");
        if (count == 0)
            category.style.visibility = 'visible';
        else
            category.style.visibility = 'hidden';
        count = count == 0 ? 1 : 0;
    }

    const element = document.getElementById('category');
    document.addEventListener('click', function ({ target }) {
        let isVisible;
        isVisible = element.contains(target);
        (count > 0) ? count++ : 0;
        if (!isVisible && count >= 3) {
            document.getElementById('category').style.visibility = "hidden";
            count = 0;
        }
    });
</script>